import React, {useCallback,useEffect} from "react";
import Particles from "react-tsparticles";
import tsParticles from "tsparticles";
import {loadPolygonMaskPlugin} from "tsparticles-plugin-polygon-mask";
import {Engine} from "@tsparticles/engine";
import {loadFull} from "tsparticles";
import particleconfig from "./configurations/particles.json";
import styles from "./styles/message.module.css";
// possible parameters can be int , float , string or boolean or objects made of them not constants/identifiers
const option :any= {
    autoPlay:true,
    polygon:{
            enable:true,
            type:"inline",
            draw :{
                enable:true,
                stroke:{
                    color:"#ffffff",
                    width:1,
                    opacity:0.1,
                },
            },
            inline: {
                arrangement: "equidistant"
            },
            move: {
                radius:31,
                type:"path",
            },
            scale:1,
            url:"paint-palette-art.svg",
            position:{
                x:50 ,
                y:50
            }
        },
    background:{
        color:{
            value: "#000000"
        },
    image:"",
    position: "50% 50%",
    repeat:"no-repeat",
    size: "cover",
    opacity:1,
    },

    backgroundMask:{
        composite:"destination-out" as GlobalCompositeOperation,
        cover:{
            opacity:1,
            color:{
                value:"",
            }
        },
        enable:false,
    },
    clear:true,
    // defaultThemes:{},
    delay:0,
    fullScreen:{
        enable:true ,
        zIndex:0
    },
    detectRetina:true,
    duration:0,
    fpsLimit:120,
    interactivity:{
        detectsOn:"window",
        events:{
            onHover:{
                enable:true,
                mode:"bubble",
                parallax:{
                    enable:false,
                    force:2,
                    smooth:10,
                }
            },
            resize: {
                delay:0.5,
                enable:true,
            },
        },
        modes :{
            trail:{ delay:1,
                pauseOnStop:false,
                quantity:1,
            },
            attract:{
                distance:200,
                duration:0.4,
                easing:"ease-out-quad",
                factor:1,
                maxSpeed:50,
                speed:1,
            },
            bounce:{
                distance:200,
            },
            bubble:{
                distance:40,
                duration:2,
                mix:false,
                opacity:8,
                size:6,
                divs:{
                    distance:200,
                    duration:0.4,
                    mix:false,
                }
            },
            connect:{
                distance:80,
                links:{
                    opacity:0.5
                },
            },
            grab:{
                distance:400,
                links:{
                    blink:false,
                    consent:false,
                    opacity:1
                }
            },
            push:{
                default:true,
                quantity:4,
            },
            remove:{
                quantity:2,
            },
            repulse:{
                distance:200,
                duration:0.4,
                factor:100,
                speed:1,
                maxSpeed:50,
                easing:"ease-out-quad",
                divs:{
                    distance:200,
                    duration:0.4,
                    factor:100,
                    speed:1,
                    maxSpeed:50,
                    easing:"ease-out-quad",
                    // selectors:{},    // selectors on mentioned cause blackout
                },
            },
            slow:{
                factor:1,
                radius:0,
            },
            particle:{
                replaceCursor:false,
                pauseOnStop:false,
                stopDelay:0,
            },
            light:{
                area:{
                    gradient:{
                        start:{
                            value:"#ffffff",
                        },
                        stop:{
                            value:"#000000",
                        },
                    },
                },
                shadow:{
                    color:{
                        value:"#000000"
                    },
                    length:2000,
                }
            }
        }
    },
    manualParticles:[],
    particles:{
        bounce:{
            horizontal:{
                value:1
            },
            vertical:{
                value:1
            }
        },
        collisions:{
            absorb:{
                speed:2,
            },
            bounce:{
                horizontal:{
                    value:1
                },
                vertical:{
                    value:1
                },
            },
            enable:false,
            maxSpeed:50,
            mode:"bounce",
            overlap:{
                enable:true,
                retries:0,
            }
        },
        color:{
            value:"#ffffff",
            animation:{
                h:{
                    count:0,
                    enable:false,
                    speed:1,
                    decay:0,
                    delay:0,
                    sync:true,
                    offset:0,
                },
                s:{
                    count:0,
                    enable:false,
                    speed:1,
                    decay:0,
                    delay:0,
                    sync:true,
                    offset:0,
                },
                l:{
                    count:0,
                    enable:false,
                    speed:1,
                    decay:0,
                    delay:0,
                    sync:true,
                    offset:0,
                },
            }
        },
        effect:{
            close:true,
            fill:true,
        },
        move:{
            angle:{
                offset:0,
                value:90,
            },
            attract:{
                distance:200,
                enable:false,
                rotate:{
                    x:3000,
                    y:3000,
                },
            },
            center:{
                x:50,
                y:50,
                mode:"percent",
                radius:0,
            },
            decay:0,
            direction:"none",
            drift:0,
            enable:true,
            gravity:{
                acceleration:9.81,
                enable:false,
                inverse:false,
                maxSpeed:50,
            },
            path:{
                clamp:true,
                delay:{
                    random:{
                        enable:true,
                        minimumValue:0.1
                    },
                    value:0
                },
                enable:true,
                generator: "polynomialPathGenerator"
            },
            outModes:{
                default:"bounce",
                bottom:"bounce",
                left:"bounce",
                right:"bounce",
                top:"bounce",
            },
            random:false,
            speed:1,
            spin:{
                acceleration:3,
                enable:true
            },
            straight:false,
            trail:{
                enable:false,
                length:10,
                fillColor:"#000000"
            },
            vibrate:false,
            warp:false
        },
        
        
        number:{
            density:{
                enable:false,
                width:1920,
                height:1080
            },
            limit:{
                mode:"delete",
                value:0
            },
            value: 200,
        },
        opacity:{
            value:{
                min:0.05,
                max:0.4
            },
            animation:{
                count:0,
                enable:true,
                speed:2,
                decay:0,
                delay:0,
                sync:false,
                mode:"auto",
                startValue:"random",
                destroy:"none",
                },
            },
            reduceDuplicates:false,
            shadow:{
                blur:0,
                color:{
                    value:"#000"
                },
                enable:false,
                offset:{
                    x:0,
                    y:0,
                },
            },
            shape:{
                close:true,
                fill:true,
                type:"circle",
            },
            size:{
                value:1,
            },
            stroke:{
                width:0,
            },
            zIndex:{
                value:0,
                opacityRate:1,
                sizeRate:1,
                velocityRate:1
            },
            destroy:{
                mode:"none",
                split:{
                    count:1,
                    factor:{
                        value:3,
                    },
                    rate:{
                        value:{
                            min:4,
                            max:9,
                        }
                    },
                    sizeOffset:true,
                }
            },
            roll:{
                darken:{
                    enable:false,
                    value:0
                },
                enable:false,
                mode:"vertical",
                speed:25,
            },
            tilt:{
                value:0,
                animation:{
                    enable:false,
                    speed:0,
                    decay:0,
                    sync:false,
                },
                direction:"clockwise",
                enable:false,
            },
            life:{
                count:0,
                delay:{
                    value:0,
                    sync:false,
                },
                duration:{
                    value:0,
                    sync:false,
                },
            },
            rotate:{
                value:0,
                animation:{
                    enable:false,
                    speed:0,
                    decay:0,
                    sync:false,
                },
                direction:"clockwise",
                path:false,
            },
            links:{
                blink:false,
                color:{
                    value:"#ffffff"
                },
                enable:true,
                distance:30,
                frequency:1,
                opacity:0.4,
                width:1,
                warp:false,
            },
        },
        pauseOnBlur: true,
        pauseOnOutsideViewport:true,
        smooth:false,
        zLayers:50,
        key:"polygonMask",
        name:"Polygon Mask",
        motion:{
            disable:false,
            reduce:{
                factor:4,
                value:true,
            },
        },
        
};

const FusionStar:React.FC = ()=>{
    const particlesInit = useCallback(async (main:any)=>{
        await loadPolygonMaskPlugin(main);
        await loadFull(main)},[]);
   
    return( <div className= {`${styles.feature}`}> <Particles id= "antler"
        init={particlesInit} options={option} ></Particles>
        </div>
    );
};
export default FusionStar;
